import Head from 'next/head';
import HelloChinese from '~/components/HelloChinese';
import { Box, createTheme, CssBaseline, ThemeProvider } from '@mui/material';

const darkTheme = createTheme({
  palette: {
    mode: 'dark',
    background: {
      default: '#1a1a1a',
      paper: '#1a1a1a',
    },
  },
  typography: {
    fontFamily: 'Rubik, sans-serif;',
  },
});

export default function Home() {
  return (
    <div>
      <Head>
        <title>TypeIt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <ThemeProvider theme={darkTheme}>
        <Box sx={{ height: '100vh', maxWidth: '100vw' }}>
          <HelloChinese />
          <CssBaseline />
        </Box>
      </ThemeProvider>
    </div>
  );
}
